import jsPDF from "jspdf";

export function generatePDF(result) {
  const doc = new jsPDF();

  let y = 20;

  // Helper: Add Section Title
  const addTitle = (text) => {
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(text, 20, y);
    y += 8;
  };

  // Helper: Add Content with auto wrap
  const addText = (text) => {
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    const splitText = doc.splitTextToSize(text, 170);

    splitText.forEach((line) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
      y += 6;
    });
  };

  // Helper: Add List
  const addList = (items) => {
    items.forEach((item) => {
      addText(`• ${item}`);
    });
    y += 4;
  };

  // ================= HEADER =================
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("AI Resume Analysis Report", 20, y);
  y += 15;

  // ================= SCORE =================
  addTitle("ATS Match Score");
  addText(`${result.matchScore || 0}%`);
  y += 5;

  // ================= PRESENT SKILLS =================
  addTitle("Present Skills");
  addList(result.presentSkills || ["No data"]);

  // ================= MISSING SKILLS =================
  addTitle("Missing Skills");
  addList(result.missingSkills || ["No data"]);

  // ================= SUGGESTIONS =================
  addTitle("Suggestions");
  addList(result.suggestions || ["No suggestions"]);

  // ================= FOOTER =================
  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by AI Resume Analyzer", 20, 280);

  // Save file
  doc.save("AI_Resume_Report.pdf");
}